services:
  app:
    image: ghcr.io/lakr233/creemproxy:main
    ports:
      - "8443:8443"
    environment:
      - CREEM_API_KEY="" # remember to replace with your API key
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "5"
